### ISSUE TITLE
Updating VitaShell?

### ISSUE THREAD

**Issue by ghost** [gnmmarechal/VSOI#4]
Hi,

Thanks for creating this tweak. I would like to know how I can upgrade VitaShell from the near icon. When I open it, I am prompted to install the newest version (which I apparently have, separate from this tweak; v1.97). However, upon "installation" it just opens the other VitaShell (the one installed on my memory card, I believe) which is already the latest version.

If upgrading isn't possible, how can I undo or remove this extra VitaShell? I'm ok with losing near. If it's safe to keep both, that's also fine.

Thanks!

**Comment by gnmmarechal** [comment]
Alright, so. To update VitaShell manually, what you need to do is take the eboot.bin from the newer version (open the VPK with 7-Zip, WinRAR and the like), then put it at "vs0:app/NPXS10000/eboot.bin". 
I don't have a Vita anymore, but I'll probably add an uninstall option at some point.

**Comment by ghost** [comment]
Thanks a lot! I think that's enough for my purposes. The uninstall option would be cool but I am satisfied with your suggestion/solution.

**Comment by gnmmarechal** [comment]
Well, as I said, I don't have a Vita anymore, but unless I made a dumb mistake due to my lack of sleep, I ended up making it so VSOI uses ux0:data/vsEboot.bin instead of the one bundled with the VPK if it finds it. (By the way, if you have your original Near eboot backup, you might want to back it up elsewhere because VSOI always replaces it with the current "Near "eboot when doing its "first run")

The update is untested, but uhhh, if you have any interest in it, it's there I guess.

**Comment by ghost** [comment]
Wanted to let you know that replacing the eboot worked! Thanks again.

Thanks for making an update to the files too.
